name: Build Web

on:
  push:
    branches:
      - 'main'
    paths:
      - 'src/web/**'
      - 'src/shared/**'
      - 'test/web/**'
      - 'Web.Dockerfile'
      - '.github/workflows/build_web.yml'

jobs:

  build:
    name: Build
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
      
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: nomanova/ojeda-web
          flavor: |
            latest=true
          tags: |
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build image
        uses: docker/build-push-action@v2
        with:
          tags: ${{ steps.docker_meta.outputs.tags }}
          push: ${{ github.event_name != 'pull_request' }}
          file: ./Web.Dockerfile
          build-args: |
            SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}
