name: Build API

on:
  push:
    branches: [ main ]
    paths:
      - 'src/api/**'
      - 'src/shared/**'
      - 'test/api/**'
      - 'Api.Dockerfile'

jobs:

  build:
    name: Build
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
